### ISSUE TITLE
technical feedback

### ISSUE THREAD

**Issue by bradgarropy** [bradgarropy/dailytexascountry.com#120]
### [Daily Texas Country](https://dev.dailytexascountry.com)

- ~Level Up Tutorials Discord~
  - ~webdevcharlie~
  - ~Todd Libby~
  - ~Scott Tolinski~
- ~Frontend Guild~
  - ~Shashi Lo~
- ~PREX~
  - ~Arjun Athreya~
  - ~Abram Himmer~
  - ~Ross Brandon~
  - ~David Meadows~
- ~Search~
  - ~Eduardo Vargas~
  - ~James Delorey~
  - ~Ryan Manor~
- ~@jamesqquick~
- ~@austintoddj~
- ~Twitter~

**Comment by austintoddj** [comment]
Honestly, no complaints! Looks good, great starting point!

Keep up the good work!
